---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  labels:
    app: auctus
data:
  elasticsearch.cluster_name: "auctus-cluster"
  elasticsearch.heap_size: "4g"
  api_url: http://192.168.99.100:30002/api/v1
  frontend_url: http://192.168.99.100:30001
  nominatim_url: http://nominatim:8080/
  custom_fields: ""
  redis.conf: |
    maxmemory 500mb
    maxmemory-policy allkeys-lru
  max_cache_bytes: "50000000000"  # 50 GB
  s3.url: ""
  s3.client_url: ""
  s3.bucket_prefix: "datamart-dev-"
  gcs.project: "datamart"
  gcs.bucket_prefix: "datamart-dev-"
