---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-cluster
  labels:
    app: datamart
    what: elasticsearch
spec:
  selector:
    app: datamart
    what: elasticsearch
  ports:
  - name: transport
    protocol: TCP
    port: 9300
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  labels:
    app: datamart
    what: elasticsearch
spec:
  serviceName: elasticsearch-cluster
  replicas: 2
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: datamart
      what: elasticsearch
  template:
    metadata:
      labels:
        app: datamart
        what: elasticsearch
    spec:
      securityContext:
        runAsNonRoot: true
      initContainers:
      - name: fix-permissions
        image: busybox
        securityContext:
          runAsNonRoot: false
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        volumeMounts:
        - name: elasticsearch
          mountPath: /usr/share/elasticsearch/data
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          runAsNonRoot: false
          privileged: true
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
        securityContext:
          runAsUser: 1000
        env:
        - name: cluster.name
          value: datamart-cluster
        - name: network.host
          value: "0.0.0.0"
        - name: ES_JAVA_OPTS
          value: -Des.enforce.bootstrap.checks=true
        - name: discovery.zen.ping.unicast.hosts
          value: elasticsearch-cluster:9300
        - name: discovery.zen.minimum_master_nodes
          value: "1"
        - name: xpack.security.enabled
          value: "false"
        - name: xpack.monitoring.enabled
          value: "false"
        - name: cluster.initial_master_nodes
          value: elasticsearch-0
        # This needs special permissions that I don't know how to grant
        # - name: bootstrap.memory_lock
        #   value: "true"
        - name: ES_HEAP_SIZE
          valueFrom:
            configMapKeyRef:
              name: config
              key: elasticsearch.heap_size
        ports:
        - containerPort: 9200
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: elasticsearch
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /_cluster/health?local=true
            port: 9200
          initialDelaySeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: elasticsearch
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
