---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: secrets
data:
  # Those values need to be encoded in base64
  amqp.user: ZGF0YW1hcnQ= # "datamart"
  amqp.password: ZGF0YW1hcnQ= # "datamart"
  s3.key: ZGV2a2V5 # "devkey"
  s3.secret: ZGV2cGFzc3dvcmQ= # "devpassword"
  gcs.project: ""
  gcs.creds: ""
