---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: datamart
    what: elasticsearch
spec:
  selector:
    app: datamart
    what: elasticsearch
  ports:
  - protocol: TCP
    port: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: datamart
    what: rabbitmq
spec:
  selector:
    app: datamart
    what: rabbitmq
  ports:
  - protocol: TCP
    port: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: datamart
    what: redis
spec:
  selector:
    app: datamart
    what: redis
  ports:
  - protocol: TCP
    port: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: lazo
  labels:
    app: datamart
    what: lazo
spec:
  selector:
    app: datamart
    what: lazo
  ports:
  - protocol: TCP
    port: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: coordinator
  labels:
    app: datamart
    what: coordinator
spec:
  selector:
    app: datamart
    what: coordinator
  type: NodePort
  ports:
  - protocol: TCP
    port: 8001
    nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: apiserver
  labels:
    app: datamart
    what: apiserver
spec:
  selector:
    app: datamart
    what: apiserver
  type: NodePort
  ports:
  - protocol: TCP
    port: 8002
    nodePort: 30081
