---
apiVersion: v1
kind: Service
metadata:
  name: test-discoverer
  labels:
    app: auctus
    what: test-discoverer
spec:
  selector:
    app: auctus
    what: test-discoverer
  ports:
  - protocol: TCP
    port: 7000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-discoverer
  labels:
    app: auctus
    what: test-discoverer
    test: "true"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: auctus
      what: test-discoverer
  template:
    metadata:
      labels:
        app: auctus
        what: test-discoverer
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: discoverer
        image: auctus_test-discoverer
        args: ["testsuite"]
        imagePullPolicy: IfNotPresent
        env:
        - name: ELASTICSEARCH_HOSTS
          value: elasticsearch:9200
        - name: ELASTICSEARCH_PREFIX
          valueFrom:
            configMapKeyRef:
              name: config
              key: elasticsearch_prefix
        - name: AMQP_HOST
          value: rabbitmq
        - name: AMQP_PORT
          value: "5672"
        - name: AMQP_USER
          valueFrom:
            secretKeyRef:
              name: secrets
              key: amqp.user
        - name: AMQP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: amqp.password
        - name: S3_KEY
          valueFrom:
            secretKeyRef:
              name: secrets
              key: s3.key
        - name: S3_SECRET
          valueFrom:
            secretKeyRef:
              name: secrets
              key: s3.secret
        - name: S3_URL
          valueFrom:
            configMapKeyRef:
              name: config
              key: s3.url
        - name: S3_CLIENT_URL
          valueFrom:
            configMapKeyRef:
              name: config
              key: s3.client_url
        - name: S3_BUCKET_PREFIX
          valueFrom:
            configMapKeyRef:
              name: config
              key: s3.bucket_prefix
        - name: GCS_PROJECT
          valueFrom:
            configMapKeyRef:
              name: config
              key: gcs.project
        - name: GCS_CREDS
          valueFrom:
            secretKeyRef:
              name: secrets
              key: gcs.creds
        - name: GCS_BUCKET_PREFIX
          valueFrom:
            configMapKeyRef:
              name: config
              key: gcs.bucket_prefix
        - name: LAZO_SERVER_HOST
          value: lazo
        - name: LAZO_SERVER_PORT
          value: "50051"
