---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: datasets
  labels:
    type: local
    app: datamart
    what: datasets
spec:
  storageClassName: "manual"
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/var/lib/datamart/prod/datasets"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: datasets
spec:
  selector:
    matchLabels:
      app: datamart
      what: datasets
  storageClassName: "manual"
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: cache
  labels:
    type: local
    app: datamart
    what: cache
spec:
  storageClassName: "manual"
  capacity:
    storage: 55Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/var/lib/datamart/prod/cache"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cache
spec:
  selector:
    matchLabels:
      app: datamart
      what: cache
  storageClassName: "manual"
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 55Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: geo-data
spec:
  accessModes:
  - ReadOnlyMany
  - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: es-synonyms
spec:
  accessModes:
  - ReadOnlyMany
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi
