---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: elasticsearch
  labels:
    type: local
    app: datamart
    what: elasticsearch
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/var/lib/datamart/prod/elasticsearch"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elasticsearch
spec:
  storageClassName: ""
  selector:
    matchLabels:
      app: datamart
      what: elasticsearch
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: datasets
  labels:
    type: local
    app: datamart
    what: datasets
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/var/lib/datamart/prod/datasets"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: datasets
spec:
  storageClassName: ""
  selector:
    matchLabels:
      app: datamart
      what: datasets
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: cache
  labels:
    type: local
    app: datamart
    what: cache
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/var/lib/datamart/prod/cache"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cache
spec:
  storageClassName: ""
  selector:
    matchLabels:
      app: datamart
      what: cache
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: geo-data
  labels:
    type: local
    app: datamart
    what: geo-data
spec:
  capacity:
    storage: 300Mi
  accessModes:
  - ReadOnlyMany
  hostPath:
    path: "/var/lib/datamart/geo-data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: geo-data
spec:
  storageClassName: ""
  selector:
    matchLabels:
      app: datamart
      what: geo-data
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 300Mi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: es-synonyms
  labels:
    type: local
    app: datamart
    what: es-synonyms
spec:
  capacity:
    storage: 5Mi
  accessModes:
  - ReadOnlyMany
  hostPath:
    path: "/var/lib/datamart/es-synonyms"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: es-synonyms
spec:
  storageClassName: ""
  selector:
    matchLabels:
      app: datamart
      what: es-synonyms
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 5Mi
